language: node_js

node_js:
  - 8
  - 10
  - 12

# Build only commits on master and release tags preventing double builds for PRs
# See https://docs.travis-ci.com/user/pull-requests/#double-builds-on-pull-requests
branches:
  only:
    - master
    - /v[0-9]+\.[0-9]+\.[0-9]+(-.*)?$/

cache: npm

script:
  - npm run lint
  - npm run lint:test
  - npm run test:report

# TODO: Add npm publishing on tags
